"""phone number

Revision ID: 26cce2adff43
Revises: 324b4b0106e2
Create Date: 2025-12-14 00:34:57.396583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cce2adff43'
down_revision: Union[str, Sequence[str], None] = '324b4b0106e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('phonenumber', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'phonenumber')
    # ### end Alembic commands ###
